import { Transaction } from "./TransactionsTable";

export const DummyTransactions: Transaction[] = [
  {
    transaction_category: "Top Up",
    source_fund: "Bank BCA",
    description: "Top up via BCA Virtual Account",
    amount: "500000",
    transaction_time: new Date("2025-08-01T09:15:00"),
    recipent: "My Wallet",
  },
  {
    transaction_category: "Transfer",
    source_fund: "Wallet",
    description: "Sent money to friend",
    amount: "150000",
    transaction_time: new Date("2025-08-02T14:22:00"),
    recipent: "John Doe",
  },
  {
    transaction_category: "Payment",
    source_fund: "Wallet",
    description: "Paid electricity bill",
    amount: "350000",
    transaction_time: new Date("2025-08-03T19:05:00"),
    recipent: "PLN",
  },
  {
    transaction_category: "Top Up",
    source_fund: "Bank Mandiri",
    description: "Top up via Mandiri Internet Banking",
    amount: "1000000",
    transaction_time: new Date("2025-08-04T08:45:00"),
    recipent: "My Wallet",
  },
  {
    transaction_category: "Transfer",
    source_fund: "Wallet",
    description: "Transfer to savings account",
    amount: "250000",
    transaction_time: new Date("2025-08-05T16:10:00"),
    recipent: "Bank BRI",
  },
  {
    transaction_category: "Payment",
    source_fund: "Wallet",
    description: "Bought movie tickets",
    amount: "120000",
    transaction_time: new Date("2025-08-06T12:30:00"),
    recipent: "Cinema XXI",
  },
  {
    transaction_category: "Top Up",
    source_fund: "Bank BNI",
    description: "Top up via BNI Mobile",
    amount: "200000",
    transaction_time: new Date("2025-08-07T11:20:00"),
    recipent: "My Wallet",
  },
  {
    transaction_category: "Transfer",
    source_fund: "Wallet",
    description: "Sent pocket money",
    amount: "300000",
    transaction_time: new Date("2025-08-08T07:50:00"),
    recipent: "Jane Doe",
  },
  {
    transaction_category: "Payment",
    source_fund: "Wallet",
    description: "Paid Spotify subscription",
    amount: "54999",
    transaction_time: new Date("2025-08-09T21:40:00"),
    recipent: "Spotify",
  },
  {
    transaction_category: "Payment",
    source_fund: "Wallet",
    description: "Grab ride to airport",
    amount: "85000",
    transaction_time: new Date("2025-08-10T10:05:00"),
    recipent: "Grab",
  },
];
